import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://gameslib.net";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Gameslib — Free PC Games Download",
    template: "%s | Gameslib",
  },
  description: "Download free PC games with direct links, system requirements, and installation guides. Browse 500+ games across all genres.",
  keywords: const gamesLibKeywords = [
    // Branded Keywords
    "gameslib",
    "gameslib.net",
    "games lib",
    "gameslib download",
    "gameslib pc",
    "gameslib free games",
    "gameslib official site",
    "gameslib reviews",
    "gameslib safe download",
    "gameslib legit",
    
    // Core Free PC Games Keywords
    "free PC games",
    "download free PC games",
    "best free PC games",
    "free computer games",
    "PC games free download",
    "games for PC free",
    "free games to download for PC",
    "top free PC games",
    "latest free PC games",
    "new free PC games",
    "free full PC games",
    "free PC games no survey",
    "free PC games no account",
    "PC games without payment",
    "gratis PC games",
    "games free download PC",
    "free PC gaming downloads",
    
    // Pre-installed & Direct Download
    "pre-installed PC games",
    "download pre-installed games",
    "PC games pre-installed free",
    "portable PC games",
    "free portable games download",
    "games no installation required",
    "PC games ready to play",
    "instant play PC games",
    "pre-configured PC games",
    "direct play PC games",
    "games without setup",
    "compressed PC games",
    "highly compressed PC games",
    "direct download games PC",
    "PC games direct link download",
    "fast download PC games",
    "secure game downloads PC",
    "trusted game download site",
    "safe PC game downloads",
    "download games no torrent",
    
    // Genre-Based Keywords
    "free action PC games",
    "download action games free",
    "best free action games PC",
    "free adventure PC games",
    "download adventure games free",
    "free RPG PC games",
    "download RPG games free",
    "best free RPG games PC",
    "free simulation PC games",
    "download simulation games free",
    "free strategy PC games",
    "download strategy games free",
    "free horror PC games",
    "download horror games free",
    "free racing PC games",
    "download racing games free",
    "free sports PC games",
    "download sports games free",
    "indie games free PC",
    "puzzle games free download",
    "casual games free PC",
    "open world games free PC",
    "fighting games PC free",
    "platform games free PC",
    "shooter games free PC",
    "survival games free PC",
    "sandbox games free PC",
    "mmorpg games free PC",
    
    // Popular Game Titles
    "God of War PC download free",
    "Red Dead Redemption 2 PC free",
    "Forza Horizon 5 PC download",
    "Palworld PC download free",
    "Minecraft PC download free",
    "Grand Theft Auto V free PC",
    "Cyberpunk 2077 PC free download",
    "The Witcher 3 PC free",
    "Elden Ring PC free download",
    "Call of Duty free PC",
    "Valorant PC download free",
    "Fortnite PC free download",
    "Apex Legends PC download",
    "Counter-Strike 2 PC download",
    "League of Legends PC download",
    "Overwatch 2 PC download",
    "Destiny 2 PC download",
    "Warframe PC download",
    "Genshin Impact PC download",
    "Among Us PC free download",
    "Fall Guys PC free",
    "Rocket League PC free",
    "Terraria PC free download",
    "Stardew Valley PC free",
    "Hades PC free download",
    "Dead by Daylight PC free",
    "Phasmophobia PC free download",
    "Valheim PC free download",
    "It Takes Two PC free",
    "A Way Out PC free download",
    
    // Long-tail Keywords
    "free action RPG PC games direct download",
    "download latest horror games PC no install",
    "best free open world games PC pre-installed",
    "highly compressed strategy games for laptop free",
    "safe site to download free PC games without account",
    "new free adventure games with controller support PC",
    "fastest way to download PC games free",
    "complete list of free pre-installed PC games",
    "gameslib download trending games",
    "gameslib free games collection",
    "how to play pre-installed PC games",
    "where to find free portable games for PC",
    "download free indie games PC direct link",
    "free PC games with high graphics no install",
    "best free racing games for low end PC",
    "free puzzle games for Windows 10 no ads",
    "download latest RPG games PC portable",
    "free strategy games like Age of Empires PC",
    "gameslib alternative free download",
    "free PC games for offline play",
    "best single-player PC games free download",
    "free multiplayer PC games direct download",
    "download free story driven PC games",
    "free PC games for older computers",
    
    // Platform Specific
    "Steam PC games free",
    "Epic Games free PC",
    "GOG games free PC",
    "free PC games Windows 10",
    "free PC games Windows 11",
    "PC games for Mac free",
    "console games PC version free",
    "latest PC games free download",
    
    // Problem/Solution Keywords
    "hassle-free game downloads",
    "easy PC game download",
    "games without lengthy installation",
    "bypass game installation",
    "quick game setup PC",
    "reliable game downloads",
    "trusted source for PC games",
    "virus-free game downloads",
    "safe game download sites",
    "no malware game downloads",
    
    // Technical Keywords
    "PC game system requirements",
    "low spec PC games free",
    "high performance PC games free",
    "DirectX PC games free",
    "OpenGL PC games free",
    "controller support PC games free",
    "keyboard mouse PC games free",
    "4K PC games free download",
    "HDR PC games free",
    "ray tracing PC games free",
    
    // Gaming Community Keywords
    "PC gaming community",
    "free games recommendations",
    "gaming forums PC free games",
    "PC game reviews free",
    "gaming news free PC games",
    "upcoming free PC games 2026",
    "trending PC games free",
    "popular PC games this month",
    "best new PC games free",
    "hidden gem PC games free",
    
    // Specific Features
    "offline PC games free",
    "single player PC games free",
    "multiplayer PC games free",
    "co-op PC games free",
    "split screen PC games free",
    "local multiplayer PC games free",
    "online multiplayer PC games free",
    "cross platform PC games free",
    "cloud save PC games free",
    "achievement system PC games free",
    
    // Additional Game Variations
    "puzzle adventure games PC free",
    "tower defense games PC free",
    "city builder games PC free",
    "farming simulator games PC free",
    "space exploration games PC free",
    "zombie survival games PC free",
    "post apocalyptic games PC free",
    "medieval games PC free",
    "sci-fi games PC free",
    "fantasy games PC free",
    "retro style games PC free",
    "pixel art games PC free",
    "2D platformer games PC free",
    "3D adventure games PC free",
    "first person shooter games PC free",
    "third person action games PC free",
    "turn based strategy games PC free",
    "real time strategy games PC free",
    "card games PC free",
    "board games PC free",
    
    // Niche & Specific Searches
    "educational PC games free",
    "kids PC games free download",
    "family friendly PC games free",
    "mature content PC games free",
    "indie developer PC games free",
    "early access PC games free",
    "beta PC games free download",
    "alpha PC games free",
    "game mods PC free download",
    "game patches PC free",
    "game updates PC free",
    "dlc content PC games free",
    "expansion packs PC games free",
    "complete edition PC games free",
    "director's cut PC games free",
    "remastered PC games free",
    "remake PC games free download",
    "classic PC games free download",
    "vintage PC games free",
    "abandonware PC games free",
    
    // Performance & Quality Keywords
    "60fps PC games free",
    "120fps PC games free",
    "ultra settings PC games free",
    "low latency PC games free",
    "smooth gameplay PC games free",
    "optimized PC games free",
    "bug free PC games download",
    "stable PC games free",
    "tested PC games free download",
    "verified PC games free",
    "quality assured PC games free",
    "premium PC games free download",
    "AAA PC games free",
    "indie AAA PC games free",
    "blockbuster PC games free",
    
    // User Experience Keywords
    "easy download PC games",
    "simple PC games download",
    "one click PC games download",
    "instant PC games download",
    "fast PC games download",
    "quick PC games setup",
    "user friendly PC games site",
    "intuitive PC games download",
    "streamlined PC games access",
    "convenient PC games library",
    "organized PC games collection",
    "curated PC games selection",
    "handpicked PC games free",
    "premium PC games experience",
    "professional PC games service"
],
  authors: [{ name: "Gameslib", url: SITE_URL }],
  creator: "Gameslib",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Gameslib",
    title: "Gameslib — Free PC Games Download",
    description: "Download free PC games with direct links and installation guides.",
    images: [{ url: "/og-image.jpg", width: 1200, height: 630, alt: "Gameslib" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Gameslib — Free PC Games Download",
    description: "Download free PC games with direct links and installation guides.",
    images: ["/og-image.jpg"],
  },
  robots: { index: true, follow: true },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen flex flex-col bg-g-bg text-g-text">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
