import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'game',
  title: 'Games',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Title', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'genres',
      title: 'Genres',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'RPG', value: 'RPG' },
          { title: 'Action', value: 'Action' },
          { title: 'Adventure', value: 'Adventure' },
          { title: 'Strategy', value: 'Strategy' },
          { title: 'Shooter', value: 'Shooter' },
          { title: 'Sports', value: 'Sports' },
          { title: 'Racing', value: 'Racing' },
          { title: 'Simulation', value: 'Simulation' },
          { title: 'Puzzle', value: 'Puzzle' },
          { title: 'Platformer', value: 'Platformer' },
          { title: 'Fighting', value: 'Fighting' },
          { title: 'Horror', value: 'Horror' },
          { title: 'MMORPG', value: 'MMORPG' },
          { title: 'MOBA', value: 'MOBA' },
          { title: 'Battle Royale', value: 'Battle Royale' },
        ],
      },
    }),
    defineField({ name: 'platforms', title: 'Platforms', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'rating', title: 'Rating', type: 'number', validation: (Rule) => Rule.min(0).max(5) }),
    defineField({ name: 'downloads', title: 'Downloads', type: 'number', initialValue: 0 }),
    defineField({ name: 'releaseDate', title: 'Release Date', type: 'date' }),
    defineField({ name: 'size', title: 'Size', type: 'string' }),
    defineField({ name: 'isPublished', title: 'Published', type: 'boolean', initialValue: true }),
  ],
});
